# Generated by Django 3.0.3 on 2020-05-13 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_auto_20200513_1626'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='body_txt',
            new_name='picname',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='short_txt',
            new_name='picurl',
        ),
        migrations.AddField(
            model_name='stock',
            name='divest',
            field=models.CharField(default='-', max_length=15),
        ),
        migrations.AddField(
            model_name='stock',
            name='invest',
            field=models.CharField(default='-', max_length=15),
        ),
        migrations.AddField(
            model_name='stock',
            name='txt',
            field=models.TextField(default='-'),
        ),
    ]
