# Generated by Django 3.0.3 on 2020-07-03 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_auto_20200703_0940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='picname',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='picurl',
        ),
    ]
