# Generated by Django 3.0.3 on 2020-07-02 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20200702_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='email',
            field=models.CharField(max_length=90),
        ),
    ]
